### ISSUE TITLE
拉去镜像时要求拉去版本报错。

### ISSUE THREAD

**Issue by 98Kstar** [ki9mu/ARL-plus-docker#1]
docker-compose up -d 之后在拉取您的镜像时候显示：ERROR: pull access denied for ki9mu/arl-ki9mu, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
然后我docker login之后显示** Message: 13:58:11.376: Remote error from secret service: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files
Error saving credentials: error storing credentials - err: exit status 1, out: `The name org.freedesktop.secrets was not provided by any .service files`
望帮助解决。

**Comment by ki9mu** [comment]
可以了，你再试试，建议私聊我加个ip白名单，微信newenghost

**Comment by 98Kstar** [comment]
师傅微信号搜不到您的哇

**Comment by ki9mu** [comment]
ends
