### ISSUE TITLE
关于oneforall

### ISSUE THREAD

**Issue by xjp08** [ki9mu/ARL-plus-docker#14]
这个不需要单独下载oneforall项目吗？直接配置oneforall-config/setting.py 就可以？

**Comment by ki9mu** [comment]
不需要，只用oneforall的话使用这个：[v2.7.1版本](https://github.com/ki9mu/ARL-plus-docker/releases/tag/v2.7.1)

**Comment by xjp08** [comment]
好的，v2.7.1版本是没有原版ARL指纹统计这一项吗?
![image](https://github.com/ki9mu/ARL-plus-docker/assets/104262157/6096c83e-7726-4639-8c64-a6ece6b48246)

**Comment by xjp08** [comment]
> 不需要，只用oneforall的话使用这个：[v2.7.1版本](https://github.com/ki9mu/ARL-plus-docker/releases/tag/v2.7.1)

作者大大，可以回复一下上面关于指纹统计的问题吗

**Comment by ki9mu** [comment]
> > 不需要，只用oneforall的话使用这个：[v2.7.1版本](https://github.com/ki9mu/ARL-plus-docker/releases/tag/v2.7.1)
> 
> 作者大大，可以回复一下上面关于指纹统计的问题吗

是的，由于是基于之前基于老版本改的，那会ARL还没有推出指纹统计功能

**Comment by ki9mu** [comment]
新版有了
