### ISSUE TITLE
external volume "" not found

### ISSUE THREAD

**Issue by vbnmjj** [ki9mu/ARL-plus-docker#21]
[root@sevty9zr ARL-plus-docker-3.0.0]# docker-compose up  -d
external volume "" not found

**Comment by ki9mu** [comment]
docker volume create arl_db

**Comment by vbnmjj** [comment]
谢谢您  ，执行docker volume create arl_db创建了一个volume  就能继续成功运行arl了。但是这个卷竟然不会自动创建。

**Comment by ki9mu** [comment]
没有办法自动创建，因为是宿主机
