### ISSUE TITLE
请问如何添加指纹？

### ISSUE THREAD

**Issue by IGNiT3-R** [ki9mu/ARL-plus-docker#23]
如题，请问大佬如何添加指纹？

**Comment by ki9mu** [comment]
![image](https://github.com/user-attachments/assets/93adf18f-cf45-49d4-ad66-965d199e7e99)
[指纹数据.json](https://github.com/user-attachments/files/16371027/default.json)

**Comment by IGNiT3-R** [comment]
> ![image](https://private-user-images.githubusercontent.com/47977616/351977714-93adf18f-cf45-49d4-ad66-965d199e7e99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4OTE3NTMsIm5iZiI6MTcyMTg5MTQ1MywicGF0aCI6Ii80Nzk3NzYxNi8zNTE5Nzc3MTQtOTNhZGYxOGYtY2Y0NS00OWQ0LWFkNjYtOTY1ZDE5OWU3ZTk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDA3MTA1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4ZjE1Mzk2YTVhYjlhOWFjMDU2YTk5ZTZiYzE1MjU4NjY0MzU1ODZiYTAwYWVkYTkxMjJmOGMyNDgyNDcyM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L8vjGeGOznZbkAAeBYPBmrLtKgavCFxfDTxhvMrxoVE)

感谢大佬
