### ISSUE TITLE
target 包含在禁止域名内

### ISSUE THREAD

**Issue by allblue147** [ki9mu/ARL-plus-docker#3]
探测自己学校的资产出现：包含在禁止域名内，怎么解决

**Comment by ki9mu** [comment]
改docker-config.yaml

**Comment by LucifielHack** [comment]
> 修改docker-config.yaml

更改了docker-config.yaml，并且进入前三个容器修改了app/config.py后依然显示gov在白名单，这个应该怎么解决啊
