### ISSUE TITLE
DB-GET-Subdomains 会卡死

### ISSUE THREAD

**Issue by okoling** [ki9mu/ARL-plus-docker#4]
![image](https://user-images.githubusercontent.com/90396284/170682562-5e5058c1-5447-4f5f-ba68-230ed0b36c08.png)

![image](https://user-images.githubusercontent.com/90396284/170682585-95c36194-ba3e-4256-90e4-b848aa6c94ee.png)

**Comment by ki9mu** [comment]
在白名单里吗，是v2.6.1版本吗

**Comment by ki9mu** [comment]
验证了，你这是老版本v2.6.0，新版本DB-GET-Subdomains顺序在第一个，同时由于有人扫描hackone导致数据库内数据很奇怪，原数据库提取了一部分关键数据，其他的都删了，所以老版本的数据库连不上

**Comment by okoling** [comment]
如何判断版本呢，我已经安装文档更新了
`git pull`  更新后 `docker-compose up -d` 启动的

**Comment by ki9mu** [comment]
确实确实，后面改改，docker ps看下tag是不是v2.6.1或者直接手动改docker-compose.yml把3个镜像都改成v2.6.1，然后docker-compose up -d

**Comment by ki9mu** [comment]
发现了，是我的问题，没对数据库连接做判断，代码已修改，重新拉取镜像即可

**Comment by ki9mu** [comment]
新版本已发布v2.6.2

**Comment by okoling** [comment]
v2.6.2 做了哪些更改，刚更新没来的及测试

**Comment by ki9mu** [comment]
不在白名单里不会502，其他不变
