### ISSUE TITLE
altDns 替代

### ISSUE THREAD

**Issue by log4she11** [ki9mu/ARL-plus-docker#7]
![regulator_res2](https://user-images.githubusercontent.com/6874179/197724212-fcf29d98-0189-4d67-ac93-229864ad8b40.png)

regulator 和 dnsgen 命中率更高

**Comment by log4she11** [comment]
[regulator](https://github.com/cramppet/regulator)

**Comment by ki9mu** [comment]
冲

**Comment by ki9mu** [comment]
开发中...即将添加
